spring.application.name=WiproEurekaProducerImplementation
#producer project(Restaurant) server port number is 8081
server.port=8081

#this service(REST API'S)Register with Eureka Server
eureka.client.service-url.default-zone=http://localhost:8761


